### ISSUE TITLE
[Bug]: urllib3 removed DEFAULT_CIPHERS

### ISSUE THREAD

**Issue by solipsis-project** [FurryCoders/FALocalRepo#8]
### Version

4.4.3

### What happened?

urllib3 released a backwards incompatible change that removes the DEFAULT_CIPHERS field.

As a result, attempting to run FALocalRepo after a clean install with the current dependencies results in the error below.

To fix this, we need to pin FALocalRepo to an earlier version of urllib3:

```
poetry add urllib3<2
```

### How to reproduce the bug?

In a fresh poetry environment:

```
poetry add falocalrepo
poetry install
falocalrepo --version
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\Scripts\falocalrepo.exe\__main__.py", line 4, in <module>
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\falocalrepo\__init__.py", line 1, in <module>
    from .console import app
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\falocalrepo\console\__init__.py", line 1, in <module>
    from .app import app
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\falocalrepo\console\app.py", line 7, in <module>
    import faapi
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\faapi\__init__.py", line 2, in <module>
    from .base import FAAPI
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\faapi\base.py", line 10, in <module>
    from .connection import CloudflareScraper
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\faapi\connection.py", line 12, in <module>
    from cfscrape import CloudflareScraper  # type: ignore
  File "C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\cfscrape\__init__.py", line 19, in <module>
    from urllib3.util.ssl_ import create_urllib3_context, DEFAULT_CIPHERS
ImportError: cannot import name 'DEFAULT_CIPHERS' from 'urllib3.util.ssl_' (C:\Users\...\AppData\Local\pypoetry\Cache\virtualenvs\falr-05-2023-V98AjTAw-py3.10\lib\site-packages\urllib3\util\ssl_.py)
```

**Comment by MatteoCampinoti94** [comment]
Thanks for opening the issue!

The issue is with the cfscrape library, it hasn't been updated in over three years now and I have been looking for alternatives.

I will update the FAAPI dependencies to set cfscrape as optional and exclude urllib3 >=2.0.0 if it is selected.

**Comment by MatteoCampinoti94** [comment]
I just pushed a new patch with [version 4.4.4](https://github.com/FurryCoders/FALocalRepo/releases/tag/v4.4.3) using the new [faapi 3.11.0](https://pypi.org/project/faapi/3.11.0/).

faapi does not use cfscrape anymore, all tests are passing on multiple machines and IP addresses using just requests so it should be fine.

Just update to the new version and it will work again :)
